//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp.Internal.XA.Resources
{
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class for looking up localized (formatted) strings.
    ///This is a Server Side Strings Resource File. It may contain only string entries.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Ice.Explorer.SingleFileGenerators.StringsDesignerGenerator", "3.2.100.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Strings : Ice.Resources.StringsBase<Erp.Internal.XA.Resources.Strings>
    {
        
        protected Strings()
        {
        }
        
        /// <summary>
        /// String: 'Not Started'.
        /// </summary>
        internal static string NotStarted
        {
            get
            {
                return GetString("NotStarted");
            }
        }
        
        /// <summary>
        /// String: 'In Process'.
        /// </summary>
        internal static string InProcess
        {
            get
            {
                return GetString("InProcess");
            }
        }
        
        /// <summary>
        /// String: 'Completed'.
        /// </summary>
        internal static string Completed
        {
            get
            {
                return GetString("Completed");
            }
        }
        
        /// <summary>
        /// String: 'SubContract'.
        /// </summary>
        internal static string SubContract
        {
            get
            {
                return GetString("SubContract");
            }
        }
        
        /// <summary>
        /// String: 'Internal'.
        /// </summary>
        internal static string Internal
        {
            get
            {
                return GetString("Internal");
            }
        }
        
        /// <summary>
        /// String: 'Production Job'.
        /// </summary>
        internal static string MFG
        {
            get
            {
                return GetString("MFG");
            }
        }
        
        /// <summary>
        /// String: 'Project Job'.
        /// </summary>
        internal static string PRJ
        {
            get
            {
                return GetString("PRJ");
            }
        }
        
        /// <summary>
        /// String: 'Service Job'.
        /// </summary>
        internal static string SRV
        {
            get
            {
                return GetString("SRV");
            }
        }
    }
}
